version: 0.0
os: linux
files:
  - source: target/myapp.war
    destination: /var/lib/tomcat8/webapps
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: root

